---
- name: Launch JVM
  hosts: localhost
  become: no
  vars:
      container_name: single-core-jdk-jmx-ansible
      ram_in_bytes: 33554432
      swap_memory_in_bytes: 0
      dns_ttl: 30
      jmx_port: 2020
      image: singlecorejmxansible_single-core-jdk-jmx-ansible:latest
  tasks:
      - name: Stopping the container
        shell: "docker stop {{ container_name }} || true"

      - name: Removing the container
        shell: "docker rm --force=true {{ container_name }} || true"

      - name: Running the container
        command: "docker run --cpus 1
                             --detach
                             --name {{ container_name }}
                             --net host
                             --rm
                             --memory {{ ram_in_bytes }}
                             --memory-swap {{ swap_memory_in_bytes }}
                             --volume /var/run/docker.sock:/var/run/docker.sock
                             {{ image }}
                             java -server
                                  -XX:+UnlockExperimentalVMOptions
                                  -XX:+UseCGroupMemoryLimitForHeap
                                  -XX:+ScavengeBeforeFullGC
                                  -XX:+CMSScavengeBeforeRemark
                                  -XX:+UseSerialGC
                                  -XX:MinHeapFreeRatio=20
                                  -XX:MaxHeapFreeRatio=40
                                  -XX:GCTimeRatio=4
                                  -XX:AdaptiveSizePolicyWeight=90
                                  -Dsun.net.inetaddr.ttl={{ dns_ttl }}
                                  -Dcom.sun.management.jmxremote.port={{ jmx_port }}
                                  -Dcom.sun.management.jmxremote.rmi.port={{ jmx_port }}
                                  -Dcom.sun.management.jmxremote.authenticate=false
                                  -Dcom.sun.management.jmxremote.ssl=false
                                  Hello"
